import { ROUTE_LIQUIDITY_ADD_LIQUIDITY, ROUTE_LIQUIDITY_MY_LIQUIDITY, ROUTE_LIQUIDITY_POOLS, ROUTE_LIQUIDITY_TOKENS } from '../router/routes';

export const LIQUIDITY_VIEW = {
  LIQUIDITY_LIST: 'LIQUIDITY_LIST',
  REMOVE_LIQUIDITY: 'REMOVE_LIQUIDITY',
  ADD_LIQUIDITY: 'ADD_LIQUIDITY',
  CREATE_A_PAIR: 'CREATE_A_PAIR',
};

export const LIQUIDITY_TOKENS = {
  label: 'TOKENS',
  route: ROUTE_LIQUIDITY_TOKENS,
};
export const LIQUIDITY_POOLS = {
  label: 'POOLS',
  route: ROUTE_LIQUIDITY_POOLS,
};
export const LIQUIDITY_MY_LIQUIDITY = {
  label: 'MY LIQUIDITY',
  route: ROUTE_LIQUIDITY_MY_LIQUIDITY,
};
export const LIQUIDITY_ADD_LIQUIDITY = {
  label: 'ADD LIQUIDITY',
  route: ROUTE_LIQUIDITY_ADD_LIQUIDITY,
};
